### ISSUE TITLE
Huge Multi-Instance Vault data problem

### ISSUE THREAD

**Issue by emre-saritas** [dig/ender-vaults#13]
Hello dear developers,

We have a server with 300+ players. Our Survival gamemode uses 5 different minecraft server instances and they all connected to SQL Vault database. But we have a huge problem with EnderVaults. Somehow, when player quits from the server and joins back after a while, this player's vault glitches and generally clears. I can say that this problem happens a lot. Like A LOT A LOT man. Everyday we receive tickets of cleared vaults, duped inventories with vault plugin. 

Some players say it happens after restarts.
Some players say it happens after do server switch between survival and skyblock modes (they both use EnderVaults but different database).
Some players say it happens when server kicks me.

**Comment by dig** [comment]
What is your load-delay in the config.yml?

**Comment by emre-saritas** [comment]
5 secs, but we also tried 10 secs. It didnt work.

**Comment by emre-saritas** [comment]
I just found an error log:

[12:45:38] [Craft Scheduler Thread - 6341 - EnderVaults/ERROR]: [com.github.dig.endervaults.bukkit.storage.HikariStorage] [EnderVaults] Error while executing query.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.github.dig.endervaults.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695) ~[?:?]
	at com.github.dig.endervaults.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
	at com.github.dig.endervaults.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
	at com.github.dig.endervaults.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at com.github.dig.endervaults.bukkit.storage.HikariStorage.get(HikariStorage.java:233) ~[?:?]
	at com.github.dig.endervaults.bukkit.storage.HikariStorage.load(HikariStorage.java:102) ~[?:?]
	at com.github.dig.endervaults.bukkit.vault.BukkitVaultPersister.load(BukkitVaultPersister.java:25) ~[?:?]
	at com.github.dig.endervaults.bukkit.BukkitListener.lambda$onJoin$0(BukkitListener.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Airplane-12]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Airplane-12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
